### ISSUE TITLE
Dragged item is not animated when dragging ends

### ISSUE THREAD

**Issue by StudeApps** [Spicy-Sparks/react-native-flashdrag-list#1]
When using this draggable flashlist, it seems like no animation occurs when the user stops dragging the item. Instead, there is a delay and the dragged item will suddenly 'teleport'. I don't know if this is the intended behaviour or not.
This also happens in the provided example (Android)

Thank you for your work

**Comment by geroale** [comment]
Hello, I am not sure if I understand your example correctly, but that behaviour is intended. At the moment we don't have the resources to implement the enhancement, maybe we will add it in the near future. PRs are welcome though :)

**Comment by StudeApps** [comment]
Thank you very much! I'll see what I can do :)

**Comment by geroale** [comment]
Latest version should support this end animation too

**Comment by StudeApps** [comment]
It works as expected! Thank you for your hard work
