### ISSUE TITLE
begin drag is a not a function

### ISSUE THREAD

**Issue by roo12312** [Spicy-Sparks/react-native-flashdrag-list#2]
Hi,

Begin drag is not a function its just returning a boolean value

```
TypeError: onLongPress is not a function (it is false), js engine: hermes
```

**Comment by kaitoo1** [comment]
@rohankm this is probably a bit late for you but sharing in case it helps anyone else - it looks like the example in the readme is off. `beginDrag` is the 4th param not 3rd so you're probably accessing the `active` value not `beginDrag`

from FlashDragList.tsx :
```
 renderItem: (
    item: any,
    index: number,
    active: boolean,
    beginDrag: () => any
  ) => JSX.Element;```

**Comment by geroale** [comment]
Hello, yes, the issue was a mistake in the README. We updated it according to the actual library.
